### ISSUE TITLE
疑问：关于拼音、字形信息实验的疑问?

### ISSUE THREAD

**Issue by yongzhuo** [piglaker/ConfusionCluster#2]
疑问：关于拼音、字形信息实验的疑问?

1.拼音、字形的实验很不一样;
     拼音的二分类实验是很相似的字(称,程)，但是字形的二分类差别很远的偏旁部首(称, 尔)。如果训练用的是混淆词典的字形(称, 科)这种，是不是也会像拼音那样，概率也为50%左右了。因为这些在预训练的时候就比较接近了，导致很难区分;

2.会不会是bert-embedding各向异性的原因;

**Comment by piglaker** [comment]
1.是的，因为中文象形文字，形近就会意思接近
2.这个不好说了，建议研究大模型吧，大模型时代纠错不太值得做



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月27日 16:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [piglaker/ConfusionCluster] 疑问：关于拼音、字形信息实验的疑问? (Issue #2) |

疑问：关于拼音、字形信息实验的疑问?

1.拼音、字形的实验很不一样;
拼音的二分类实验是很相似的字(称,程)，但是字形的二分类差别很远的偏旁部首(称, 尔)。如果训练用的是混淆词典的字形(称, 科)这种，是不是也会像拼音那样，概率也为50%左右了。因为这些在预训练的时候就比较接近了，导致很难区分;

2.会不会是bert-embedding各向异性的原因;

**Comment by yongzhuo** [comment]
好的，谢谢作者的回复
